const MODELS = [
  // Chat / General
  { id: 'llama3.1:8b', name: 'Llama 3.1', size: '8B', ram: '4.9 GB', category: 'chat', pulls: '119M', desc: 'Meta state-of-the-art model' },
  { id: 'llama3.1:70b', name: 'Llama 3.1', size: '70B', ram: '43 GB', category: 'chat', pulls: '119M', desc: 'Meta large model' },
  { id: 'llama3.2:1b', name: 'Llama 3.2', size: '1B', ram: '1.3 GB', category: 'chat', pulls: '82M', desc: 'Meta compact model' },
  { id: 'llama3.2:3b', name: 'Llama 3.2', size: '3B', ram: '2.0 GB', category: 'chat', pulls: '82M', desc: 'Meta small model' },
  { id: 'llama3.3:70b', name: 'Llama 3.3', size: '70B', ram: '43 GB', category: 'chat', pulls: '4.1M', desc: 'Meta latest large model' },
  { id: 'qwen2.5:0.5b', name: 'Qwen 2.5', size: '0.5B', ram: '1.1 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:1.5b', name: 'Qwen 2.5', size: '1.5B', ram: '1.9 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:3b', name: 'Qwen 2.5', size: '3B', ram: '2.5 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:7b', name: 'Qwen 2.5', size: '7B', ram: '4.4 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:14b', name: 'Qwen 2.5', size: '14B', ram: '9.1 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:32b', name: 'Qwen 2.5', size: '32B', ram: '20 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen2.5:72b', name: 'Qwen 2.5', size: '72B', ram: '44 GB', category: 'chat', pulls: '40M', desc: 'Alibaba multilingual' },
  { id: 'qwen3:0.6b', name: 'Qwen 3', size: '0.6B', ram: '1.4 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3:1.7b', name: 'Qwen 3', size: '1.7B', ram: '2.0 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3:4b', name: 'Qwen 3', size: '4B', ram: '3.5 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3:8b', name: 'Qwen 3', size: '8B', ram: '5.0 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3:14b', name: 'Qwen 3', size: '14B', ram: '9.1 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3:30b', name: 'Qwen 3', size: '30B', ram: '19 GB', category: 'chat', pulls: '37M', desc: 'Alibaba MoE model' },
  { id: 'qwen3:32b', name: 'Qwen 3', size: '32B', ram: '20 GB', category: 'chat', pulls: '37M', desc: 'Alibaba latest generation' },
  { id: 'qwen3.5:0.8b', name: 'Qwen 3.5', size: '0.8B', ram: '1.5 GB', category: 'chat', pulls: '20M', desc: 'Alibaba multimodal' },
  { id: 'qwen3.5:2b', name: 'Qwen 3.5', size: '2B', ram: '2.0 GB', category: 'chat', pulls: '20M', desc: 'Alibaba multimodal' },
  { id: 'qwen3.5:4b', name: 'Qwen 3.5', size: '4B', ram: '3.5 GB', category: 'chat', pulls: '20M', desc: 'Alibaba multimodal' },
  { id: 'qwen3.5:9b', name: 'Qwen 3.5', size: '9B', ram: '6.0 GB', category: 'chat', pulls: '20M', desc: 'Alibaba multimodal' },
  { id: 'qwen3.5:27b', name: 'Qwen 3.5', size: '27B', ram: '17 GB', category: 'chat', pulls: '20M', desc: 'Alibaba multimodal' },
  { id: 'gemma2:2b', name: 'Gemma 2', size: '2B', ram: '1.6 GB', category: 'chat', pulls: '32M', desc: 'Google compact model' },
  { id: 'gemma2:9b', name: 'Gemma 2', size: '9B', ram: '5.4 GB', category: 'chat', pulls: '32M', desc: 'Google high-performing' },
  { id: 'gemma2:27b', name: 'Gemma 2', size: '27B', ram: '18 GB', category: 'chat', pulls: '32M', desc: 'Google large model' },
  { id: 'gemma3:270m', name: 'Gemma 3', size: '270M', ram: '0.5 GB', category: 'chat', pulls: '40M', desc: 'Google smallest' },
  { id: 'gemma3:1b', name: 'Gemma 3', size: '1B', ram: '1.5 GB', category: 'chat', pulls: '40M', desc: 'Google lightweight' },
  { id: 'gemma3:4b', name: 'Gemma 3', size: '4B', ram: '3.3 GB', category: 'chat', pulls: '40M', desc: 'Google capable' },
  { id: 'gemma3:12b', name: 'Gemma 3', size: '12B', ram: '7.1 GB', category: 'chat', pulls: '40M', desc: 'Google high-performing' },
  { id: 'gemma3:27b', name: 'Gemma 3', size: '27B', ram: '18 GB', category: 'chat', pulls: '40M', desc: 'Google most capable single GPU' },
  { id: 'mistral:7b', name: 'Mistral', size: '7B', ram: '4.4 GB', category: 'chat', pulls: '34M', desc: 'Mistral AI fast model' },
  { id: 'phi3:3.8b', name: 'Phi-3', size: '3.8B', ram: '2.2 GB', category: 'chat', pulls: '18M', desc: 'Microsoft lightweight' },
  { id: 'phi3:14b', name: 'Phi-3', size: '14B', ram: '9.1 GB', category: 'chat', pulls: '18M', desc: 'Microsoft medium' },
  { id: 'phi4:14b', name: 'Phi-4', size: '14B', ram: '9.1 GB', category: 'chat', pulls: '7.7M', desc: 'Microsoft latest' },
  { id: 'deepseek-r1:1.5b', name: 'DeepSeek R1', size: '1.5B', ram: '1.1 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },
  { id: 'deepseek-r1:7b', name: 'DeepSeek R1', size: '7B', ram: '4.4 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },
  { id: 'deepseek-r1:8b', name: 'DeepSeek R1', size: '8B', ram: '4.9 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },
  { id: 'deepseek-r1:14b', name: 'DeepSeek R1', size: '14B', ram: '9.1 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },
  { id: 'deepseek-r1:32b', name: 'DeepSeek R1', size: '32B', ram: '20 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },
  { id: 'deepseek-r1:70b', name: 'DeepSeek R1', size: '70B', ram: '43 GB', category: 'chat', pulls: '93M', desc: 'Reasoning model' },

  // Code
  { id: 'qwen2.5-coder:0.5b', name: 'Qwen 2.5 Coder', size: '0.5B', ram: '1.1 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'qwen2.5-coder:1.5b', name: 'Qwen 2.5 Coder', size: '1.5B', ram: '1.9 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'qwen2.5-coder:3b', name: 'Qwen 2.5 Coder', size: '3B', ram: '2.5 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'qwen2.5-coder:7b', name: 'Qwen 2.5 Coder', size: '7B', ram: '4.4 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'qwen2.5-coder:14b', name: 'Qwen 2.5 Coder', size: '14B', ram: '9.1 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'qwen2.5-coder:32b', name: 'Qwen 2.5 Coder', size: '32B', ram: '20 GB', category: 'code', pulls: '21M', desc: 'Code generation' },
  { id: 'codellama:7b', name: 'CodeLlama', size: '7B', ram: '3.8 GB', category: 'code', pulls: '6.2M', desc: 'Meta code model' },
  { id: 'codellama:13b', name: 'CodeLlama', size: '13B', ram: '7.8 GB', category: 'code', pulls: '6.2M', desc: 'Meta code model' },
  { id: 'codellama:34b', name: 'CodeLlama', size: '34B', ram: '20 GB', category: 'code', pulls: '6.2M', desc: 'Meta code model' },
  { id: 'codellama:70b', name: 'CodeLlama', size: '70B', ram: '43 GB', category: 'code', pulls: '6.2M', desc: 'Meta code model' },

  // Vision
  { id: 'llava:7b', name: 'LLaVA', size: '7B', ram: '4.7 GB', category: 'vision', pulls: '15M', desc: 'Vision-language model' },
  { id: 'llava:13b', name: 'LLaVA', size: '13B', ram: '7.8 GB', category: 'vision', pulls: '15M', desc: 'Vision-language model' },
  { id: 'llava:34b', name: 'LLaVA', size: '34B', ram: '20 GB', category: 'vision', pulls: '15M', desc: 'Vision-language model' },
  { id: 'llama3.2-vision:11b', name: 'Llama 3.2 Vision', size: '11B', ram: '7.8 GB', category: 'vision', pulls: '3.8M', desc: 'Meta image reasoning' },
  { id: 'llama3.2-vision:90b', name: 'Llama 3.2 Vision', size: '90B', ram: '55 GB', category: 'vision', pulls: '3.8M', desc: 'Meta image reasoning' },

  // Embedding
  { id: 'nomic-embed-text', name: 'Nomic Embed', size: '274M', ram: '0 MB', category: 'embedding', pulls: '85M', desc: 'Text embeddings' },
  { id: 'mxbai-embed-large', name: 'MXBai Embed', size: '335M', ram: '0 MB', category: 'embedding', pulls: '14M', desc: 'Large embeddings' },
  { id: 'bge-m3', name: 'BGE-M3', size: '567M', ram: '1.2 GB', category: 'embedding', pulls: '6.5M', desc: 'Multi-lingual embeddings' },
];

module.exports = MODELS;
